name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build74:
    name: PHP 7.4 Code quality check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        uses: MilesChou/composer-action/7.4@master
        with:
          args: validate --no-interaction --strict

      - name: Install dependencies
        uses: MilesChou/composer-action/7.4@master
        with:
          args: install --prefer-dist --no-progress

      - name: Check for syntax errors
        uses: MilesChou/composer-action/7.4@master
        with:
          entrypoint: ./vendor/bin/parallel-lint
          args: --exclude vendor/ .

      - name: Validate code style
        uses: MilesChou/composer-action/7.4@master
        with:
          entrypoint: ./vendor/bin/php-cs-fixer
          args: fix -v --dry-run --using-cache=no .

      - name: Static code analysis
        uses: MilesChou/composer-action/7.4@master
        with:
          entrypoint: php
          args: -d memory_limit=1G ./vendor/bin/phpstan -vvv analyse -c phpstan.neon
  test74:
    name: PHP 7.4 Code test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: MilesChou/composer-action/7.4@master
        with:
          args: install --prefer-dist --no-progress

      - name: Unit tests
        uses: MilesChou/composer-action/7.4@master
        with:
          entrypoint: ./vendor/bin/phpunit
          args: tests
  build80:
    name: PHP 8.0 Code quality check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        uses: MilesChou/composer-action/8.0@master
        with:
          args: validate --no-interaction --strict

      - name: Install dependencies
        uses: MilesChou/composer-action/8.0@master
        with:
          args: install --prefer-dist --no-progress

      - name: Check for syntax errors
        uses: MilesChou/composer-action/8.0@master
        with:
          entrypoint: ./vendor/bin/parallel-lint
          args: --exclude vendor/ .

      - name: Validate code style
        uses: MilesChou/composer-action/8.0@master
        with:
          entrypoint: ./vendor/bin/php-cs-fixer
          args: fix -v --dry-run --using-cache=no .

      - name: Static code analysis
        uses: MilesChou/composer-action/8.0@master
        with:
          entrypoint: php
          args: -d memory_limit=1G ./vendor/bin/phpstan -vvv analyse -c phpstan.neon
  test80:
    name: PHP 8.0 Code test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: MilesChou/composer-action/8.0@master
        with:
          args: install --prefer-dist --no-progress

      - name: Unit tests
        uses: MilesChou/composer-action/8.0@master
        with:
          entrypoint: ./vendor/bin/phpunit
          args: tests
